CRITICALLY_ENDANGERED_ANIMALS = [
    {"name": "Javan Rhino", "status": "Critically Endangered", "scientific_name": "Rhinoceros sondaicus"},
    {"name": "Vaquita", "status": "Critically Endangered", "scientific_name": "Phocoena sinus"},
    {"name": "Amur Leopard", "status": "Critically Endangered", "scientific_name": "Panthera pardus orientalis"},
    {"name": "Black Rhino", "status": "Critically Endangered", "scientific_name": "Diceros bicornis"},
    {"name": "Bornean Orangutan", "status": "Critically Endangered", "scientific_name": "Pongo pygmaeus"},
    {"name": "Cross River Gorilla", "status": "Critically Endangered", "scientific_name": "Gorilla gorilla diehli"},
    {"name": "Hawksbill Turtle", "status": "Critically Endangered", "scientific_name": "Eretmochelys imbricata"},
    {"name": "Saola", "status": "Critically Endangered", "scientific_name": "Pseudoryx nghetinhensis"},
    {"name": "South China Tiger", "status": "Critically Endangered", "scientific_name": "Panthera tigris amoyensis"},
    {"name": "Sumatran Elephant", "status": "Critically Endangered", "scientific_name": "Elephas maximus sumatranus"},
    {"name": "Sumatran Orangutan", "status": "Critically Endangered", "scientific_name": "Pongo abelii"},
    {"name": "Sumatran Rhino", "status": "Critically Endangered", "scientific_name": "Dicerorhinus sumatrensis"},
    {"name": "Sunda Tiger", "status": "Critically Endangered", "scientific_name": "Panthera tigris sondaica"},
    {"name": "Yangtze Finless Porpoise", "status": "Critically Endangered", "scientific_name": "Neophocaena asiaeorientalis"},
    {"name": "Philippine Eagle", "status": "Critically Endangered", "scientific_name": "Pithecophaga jefferyi"},
    {"name": "Kakapo", "status": "Critically Endangered", "scientific_name": "Strigops habroptilus"},
    {"name": "Addax", "status": "Critically Endangered", "scientific_name": "Addax nasomaculatus"},
    {"name": "Chinese Pangolin", "status": "Critically Endangered", "scientific_name": "Manis pentadactyla"},
    {"name": "Mountain Gorilla", "status": "Critically Endangered", "scientific_name": "Gorilla beringei beringei"},
    {"name": "Siamese Crocodile", "status": "Critically Endangered", "scientific_name": "Crocodylus siamensis"},
]

EXTINCT_ANIMALS = [
    {"name": "Dodo", "status": "Extinct", "scientific_name": "Raphus cucullatus"},
    {"name": "Tasmanian Tiger", "status": "Extinct", "scientific_name": "Thylacinus cynocephalus"},
    {"name": "Passenger Pigeon", "status": "Extinct", "scientific_name": "Ectopistes migratorius"},
    {"name": "Woolly Mammoth", "status": "Extinct", "scientific_name": "Mammuthus primigenius"},
    {"name": "Steller's Sea Cow", "status": "Extinct", "scientific_name": "Hydrodamalis gigas"},
    {"name": "Great Auk", "status": "Extinct", "scientific_name": "Pinguinus impennis"},
    {"name": "Caribbean Monk Seal", "status": "Extinct", "scientific_name": "Neomonachus tropicalis"},
    {"name": "Quagga", "status": "Extinct", "scientific_name": "Equus quagga quagga"},
    {"name": "West African Black Rhino", "status": "Extinct", "scientific_name": "Diceros bicornis longipes"},
    {"name": "Baiji River Dolphin", "status": "Extinct", "scientific_name": "Lipotes vexillifer"},
    {"name": "Golden Toad", "status": "Extinct", "scientific_name": "Incilius periglenes"},
    {"name": "Pyrenean Ibex", "status": "Extinct", "scientific_name": "Capra pyrenaica pyrenaica"},
    {"name": "Japanese Sea Lion", "status": "Extinct", "scientific_name": "Zalophus japonicus"},
    {"name": "Toolache Wallaby", "status": "Extinct", "scientific_name": "Macropus greyi"},
    {"name": "Atlas Bear", "status": "Extinct", "scientific_name": "Ursus arctos crowtheri"},
    {"name": "Caspian Tiger", "status": "Extinct", "scientific_name": "Panthera tigris virgata"},
    {"name": "Carolina Parakeet", "status": "Extinct", "scientific_name": "Conuropsis carolinensis"},
    {"name": "Schomburgk's Deer", "status": "Extinct", "scientific_name": "Rucervus schomburgki"},
    {"name": "Falkland Islands Wolf", "status": "Extinct", "scientific_name": "Dusicyon australis"},
    {"name": "Moa", "status": "Extinct", "scientific_name": "Dinornithidae family"},
]

